name: Deploy to Firebase Hosting
on:
  push:
    branches: [ main ]  # Only triggers on push to main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v3

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
          cache: true  # Add caching for faster builds
      
      # Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Build Web
      - name: Build Web
        run: flutter build web --release --dart-define=API_URL=http://localhost:8000
        # localhost won't work in production anyway

      # Deploy to Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GAMUDA_FLUTTER_HOMEWORK_01 }}'
          channelId: live
          projectId: gamuda-flutter-homework-01  # Make sure this matches your Firebase project ID
