name: Deploy to Firebase Hosting
on:
  push:
    branches: [ main ]  # or master, depending on your default branch
  pull_request:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v3

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'  # Specify your Flutter version
          channel: 'stable'
      
      # Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Analyze code (optional but recommended)
      - name: Analyze
        run: flutter analyze

      # Run tests (if you have any)
      - name: Run tests
        run: flutter test

      # Build Web
      - name: Build Web
        run: flutter build web --release --dart-define=API_URL=http://localhost:8000

      # Deploy to Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GAMUDA_FLUTTER_HOMEWORK_01 }}'
          channelId: live
          projectId: your-project-id  # Replace with your project ID
